"""
UrbanVerse-100K

Developer: Mingxuan Liu
Affiliation: University of Trento
Email: mingxuan.liu@unitn.it
Website: https://oatmealliu.github.io/

Description:
Utility package for accessing, exploring, and using the UrbanVerse-100K asset database.

Copyright (c) 2026, Mingxuan Liu.
"""

"""
Standalone Isaac Lab script for converting GLB assets to IsaacSim-ready USD.

This script MUST be run within an Isaac Lab environment (Isaac Sim's Python),
because it depends on ``omni.kit.asset_converter`` via Isaac Lab's
``MeshConverter``.

Usage (from Isaac Lab's Python)::

    # Via isaaclab wrapper
    isaaclab -p urbanverse_asset/_glb_to_usd.py --tasks /path/to/tasks.json

    # Or directly with Isaac Sim's Python
    python urbanverse_asset/_glb_to_usd.py --tasks /path/to/tasks.json

The *tasks.json* file is generated by ``uva.convert_glb_to_usd()`` and
contains::

    {
        "tasks": [
            {"glb": "/abs/path/to.glb", "usd_dir": "/abs/dir", "usd_name": "out.usd"},
            ...
        ]
    }

Results are written to *tasks.json* with ``"results"`` appended.
"""

# ── Isaac Sim must be launched BEFORE any omni / isaaclab imports ─────────
import importlib
import sys

_missing = []
if importlib.util.find_spec("isaacsim") is None:
    _missing.append("isaacsim")
if importlib.util.find_spec("isaaclab") is None:
    _missing.append("isaaclab")
if _missing:
    print(
        f"ERROR: This script requires Isaac Sim + Isaac Lab, but the following\n"
        f"  package(s) were not found: {', '.join(_missing)}\n"
        f"\n"
        f"  To install, run:\n"
        f"    # 1. Install IsaacSim 4.5.0\n"
        f"    pip install --upgrade pip\n"
        f"    pip install 'isaacsim[all,extscache]==4.5.0'"
        f" --extra-index-url https://pypi.nvidia.com\n"
        f"\n"
        f"    # 2. Install IsaacLab (bundled in this package)\n"
        f"    cd urbanverse_asset/IsaacLab\n"
        f"    ./isaaclab.sh --install\n"
        f"\n"
        f"  Then run this script using Isaac Lab's Python:\n"
        f"    isaaclab -p {sys.argv[0]} --tasks <tasks.json> --headless",
        file=sys.stderr,
    )
    sys.exit(1)

import argparse

parser = argparse.ArgumentParser(
    description="UrbanVerse GLB → USD converter (Isaac Lab).",
)
parser.add_argument(
    "--tasks", type=str, required=True,
    help="Path to a JSON file describing conversion tasks.",
)
parser.add_argument(
    "--collision-approximation", type=str, default="convexDecomposition",
    choices=[
        "convexDecomposition", "convexHull", "boundingCube",
        "boundingSphere", "meshSimplification", "none",
    ],
    help="Collision mesh approximation method (default: convexDecomposition).",
)
parser.add_argument(
    "--make-instanceable", action="store_true", default=False,
    help="Make the asset instanceable for efficient cloning.",
)
parser.add_argument(
    "--mass", type=float, default=None,
    help="Mass in kg to assign to converted assets.",
)

# AppLauncher injects its own CLI args (headless, etc.)
from isaaclab.app import AppLauncher  # noqa: E402

AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

# ── Imports that require the Omniverse runtime ────────────────────────────
import json  # noqa: E402
import os  # noqa: E402

from isaaclab.sim.converters import MeshConverter, MeshConverterCfg  # noqa: E402
from isaaclab.sim.schemas import schemas_cfg  # noqa: E402


def main() -> None:
    tasks_path = args_cli.tasks
    with open(tasks_path) as f:
        task_data = json.load(f)

    tasks = task_data["tasks"]

    # -- Physics properties (following the reference example) --
    if args_cli.mass is not None:
        mass_props = schemas_cfg.MassPropertiesCfg(mass=args_cli.mass)
    else:
        mass_props = None

    rigid_props = schemas_cfg.RigidBodyPropertiesCfg(
        rigid_body_enabled=True, kinematic_enabled=True,
    )
    collision_props = schemas_cfg.CollisionPropertiesCfg(
        collision_enabled=args_cli.collision_approximation != "none",
    )

    results = []

    for task in tasks:
        glb_path = task["glb"]
        usd_dir = task["usd_dir"]
        usd_name = task["usd_name"]

        os.makedirs(usd_dir, exist_ok=True)

        print(f"\n{'|' + '-' * 80 + '|'}")
        print(f"  Converting: {os.path.basename(glb_path)}")
        print(f"  Output:     {os.path.join(usd_dir, usd_name)}")
        print(f"{'|' + '-' * 80 + '|'}")

        try:
            cfg = MeshConverterCfg(
                mass_props=mass_props,
                rigid_props=rigid_props,
                collision_props=collision_props,
                asset_path=glb_path,
                force_usd_conversion=True,
                usd_dir=usd_dir,
                usd_file_name=usd_name,
                make_instanceable=args_cli.make_instanceable,
                collision_approximation=args_cli.collision_approximation,
            )
            converter = MeshConverter(cfg)
            usd_path = converter.usd_path
            print(f"  ✓ Generated USD: {usd_path}")
            results.append({"glb": glb_path, "usd": usd_path, "ok": True})
        except Exception as e:
            print(f"  ✗ Failed: {e}")
            results.append({"glb": glb_path, "usd": None, "ok": False, "error": str(e)})

    # Write results back to the same JSON file
    task_data["results"] = results
    with open(tasks_path, "w") as f:
        json.dump(task_data, f, indent=2)

    print(f"\n{'=' * 82}")
    ok_count = sum(1 for r in results if r["ok"])
    print(f"  Done: {ok_count}/{len(results)} converted successfully.")
    print(f"  Results written to: {tasks_path}")
    print(f"{'=' * 82}")


if __name__ == "__main__":
    main()
    simulation_app.close()
